import { useEffect, useState } from "react";
import { Bell, CalendarCheck, ClipboardList, FileBarChart2, LayoutDashboard, LogIn, LogOut, Menu, Settings, Users, WalletCards, X, UserRoundCog, Target, FolderOpen, MessageCircle } from "lucide-react";
import Home from "@/pages/Home";
import ChatPage from "@/pages/ChatPage";
import { authApi, type SessionUser } from "@/lib/api";
function Login({ onLogin }: { onLogin: (u: SessionUser) => void }) { const [username,setUsername]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const submit=async(e:React.FormEvent)=>{e.preventDefault();try{onLogin((await authApi.login(username,password)).user)}catch(err){setError(err instanceof Error?err.message:"تعذر الدخول")}}; return <div className="login-screen" dir="rtl"><div className="login-card"><div className="brand-mark">ع</div><h1>عبد الإله HR</h1><p>نظام إدارة رأس المال البشري المتكامل</p><form onSubmit={submit}><label>اسم المستخدم<input value={username} onChange={e=>setUsername(e.target.value)} required /></label><label>كلمة المرور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label>{error&&<div className="login-error">{error}</div>}<button className="primary-button full">تسجيل الدخول <LogIn size={17}/></button></form><small>إدارة الموظفين · الحضور · الإجازات · الرواتب · الأداء</small></div></div> }
const previewUser: SessionUser = { id: 0, username: "preview", name: "مدير النظام", role: "admin", role_label: "مدير النظام", branch: "المقر الرئيسي" };
const items = [["الرئيسية", LayoutDashboard], ["الموظفون", Users], ["الحضور والانصراف", CalendarCheck], ["الإجازات", ClipboardList], ["الرواتب", WalletCards], ["الأداء والمهام", Target], ["المستندات", FolderOpen], ["المحادثات", MessageCircle], ["التقارير", FileBarChart2]] as const;
export default function App(){const[user,setUser]=useState<SessionUser>(previewUser);const[checking,setChecking]=useState(true);const[active,setActive]=useState("الرئيسية");const[open,setOpen]=useState(false);useEffect(()=>{authApi.me().then(r=>setUser(r.user)).catch(()=>{}).finally(()=>setChecking(false))},[]);if(checking)return <div className="loading-screen">جارٍ تحميل النظام...</div>;return <div className="app-shell" dir="rtl"><aside className={`sidebar ${open?"sidebar-open":""}`}><div className="brand"><div className="brand-mark">ع</div><div><strong>عبد الإله HR</strong><span>إدارة الموارد البشرية</span></div><button className="mobile-close" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="branch-card"><span className="status-dot"/> {user.branch} <small className="demo-label">دخول افتراضي</small></div><nav>{items.map(([label,Icon])=><button key={label} className={active===label?"nav-item active":"nav-item"} onClick={()=>{setActive(label);setOpen(false)}}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="nav-bottom"><button className="nav-item"><UserRoundCog size={18}/><span>إدارة الصلاحيات</span></button><button className="nav-item"><Settings size={18}/><span>الإعدادات</span></button><button className="nav-item" onClick={()=>authApi.logout().then(()=>setUser(previewUser))}><LogOut size={18}/><span>تسجيل الخروج</span></button></div></aside><main className="main-content"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(true)}><Menu size={21}/></button><div><p className="eyebrow">الخميس، ٢٧ أغسطس ٢٠٢٦</p><h1>{active}</h1></div><div className="top-actions"><button className="icon-button notification"><Bell size={19}/><i/></button><div className="user-menu"><div className="avatar">{user.name.charAt(0)}</div><div className="user-name"><strong>{user.name}</strong><span>{user.role_label}</span></div></div></div></header>{active==="المحادثات"?<ChatPage/>:<Home module={active}/>}</main></div>}
