import { useEffect, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, CalendarDays, CheckCircle2, ChevronLeft, ClipboardList, Clock3, Download, MoreHorizontal, Plus, RefreshCw, Search, SlidersHorizontal, TrendingUp, UserRound, Wallet, X } from "lucide-react";
import { dashboardApi } from "@/lib/api";

const rates = [
  { code: "USD", name: "الدولار الأمريكي", buy: "3.745", sell: "3.755", change: "+0.12%", up: true },
  { code: "EUR", name: "اليورو", buy: "4.060", sell: "4.082", change: "−0.08%", up: false },
  { code: "GBP", name: "الجنيه الإسترليني", buy: "4.728", sell: "4.760", change: "+0.24%", up: true },
  { code: "AED", name: "الدرهم الإماراتي", buy: "1.019", sell: "1.022", change: "+0.03%", up: true },
];
const movements = [
  { id: "#TX-10482", customer: "أحمد محمد العتيبي", type: "شراء دولار", amount: "2,500 USD", local: "+ 9,387.50 ر.س", time: "منذ 8 دقائق", status: "مكتملة", color: "green" },
  { id: "#TX-10481", customer: "شركة المدار للتجارة", type: "بيع يورو", amount: "1,200 EUR", local: "− 4,872.00 ر.س", time: "منذ 24 دقيقة", status: "مكتملة", color: "red" },
  { id: "#TX-10480", customer: "سارة خالد الحربي", type: "شراء جنيه", amount: "500 GBP", local: "+ 2,364.00 ر.س", time: "منذ 41 دقيقة", status: "مكتملة", color: "green" },
  { id: "#TX-10479", customer: "مؤسسة رواسي", type: "بيع دولار", amount: "3,000 USD", local: "− 11,265.00 ر.س", time: "منذ ساعة", status: "مراجعة", color: "amber" },
];

function Stat({ title, value, sub, icon, tone }: { title: string; value: string; sub: string; icon: React.ReactNode; tone: string }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div className="stat-copy"><span>{title}</span><strong>{value}</strong><small className={sub.startsWith("+") ? "positive" : "muted"}>{sub}</small></div><MoreHorizontal size={18} className="more"/></div> }

export default function Home() {
 const [showTx, setShowTx] = useState(false); const [query, setQuery] = useState(""); const [liveRates, setLiveRates] = useState(rates); const [liveMovements, setLiveMovements] = useState(movements); const [liveStats, setLiveStats] = useState({ sales: "86,420.00", purchases: "64,280.00", profit: "22,140.00" });
 useEffect(() => { dashboardApi.get().then((data) => { if (data.currencies?.length) setLiveRates(data.currencies.map((r: any) => ({ code: r.code, name: r.name_ar, buy: r.buy_rate, sell: r.sell_rate, change: "مباشر", up: true }))); if (data.transactions?.length) setLiveMovements(data.transactions.map((t: any) => ({ id: t.id, customer: t.customer, type: t.type, amount: t.amount, local: t.local, time: "مباشر", status: t.status, color: t.color }))); if (data.stats) setLiveStats({ sales: data.stats.sales, purchases: data.stats.purchases, profit: data.stats.profit }); }).catch(() => {}); }, []);
 const filtered = liveMovements.filter(m => `${m.customer} ${m.id} ${m.type}`.includes(query));
 const saveTransaction = async () => { const customer = (document.querySelector(".transaction-modal input[placeholder='اكتب اسم العميل']") as HTMLInputElement)?.value; const amount = (document.querySelector(".transaction-modal input[placeholder='0.00']") as HTMLInputElement)?.value; if (!customer || !amount) return; await dashboardApi.createTransaction({ customer, currency: "USD", transaction_type: "buy", foreign_amount: amount }); setShowTx(false); window.location.reload(); };
 return <div className="dashboard">
   <section className="welcome-row"><div><h2>صباح الخير، محمد <span>👋</span></h2><p>إليك ملخص أداء الصندوق اليوم.</p></div><div className="date-filter"><CalendarDays size={16}/> اليوم <ChevronLeft size={15}/></div></section>
   <div className="stats-grid"><Stat title="رصيد الصندوق" value="248,650.00 ر.س" sub="+ 4.8% من أمس" icon={<Wallet size={20}/>} tone="blue"/><Stat title="إجمالي المبيعات" value={`${liveStats.sales} ر.س`} sub="+ من قاعدة البيانات" icon={<ArrowUpRight size={20}/>} tone="green"/><Stat title="إجمالي المشتريات" value={`${liveStats.purchases} ر.س`} sub="+ من قاعدة البيانات" icon={<ArrowDownLeft size={20}/>} tone="violet"/><Stat title="صافي الربح" value={`${liveStats.profit} ر.س`} sub="+ محسوب تلقائيًا" icon={<TrendingUp size={20}/>} tone="amber"/></div>
   <div className="content-grid"><section className="panel operations-panel"><div className="panel-head"><div><h3>بدء عملية جديدة</h3><p>اختر نوع العملية التي تريد تنفيذها</p></div><ClipboardList size={21}/></div><div className="operation-actions"><button className="operation buy" onClick={() => setShowTx(true)}><span><ArrowDownLeft size={22}/></span><strong>شراء عملة</strong><small>استلام عملة أجنبية</small></button><button className="operation sell" onClick={() => setShowTx(true)}><span><ArrowUpRight size={22}/></span><strong>بيع عملة</strong><small>تسليم عملة أجنبية</small></button></div><div className="quick-info"><CheckCircle2 size={16}/><span>تمت تسوية جميع العمليات حتى الآن</span><b>اليوم</b></div></section>
   <section className="panel rates-panel"><div className="panel-head"><div><h3>أسعار العملات</h3><p><span className="live-dot"/> محدثة من Django</p></div><button className="text-button" onClick={() => dashboardApi.get().catch(() => {})}><RefreshCw size={15}/> تحديث</button></div><div className="rates-list">{liveRates.map(r => <div className="rate-row" key={r.code}><div className="currency-icon">{r.code === "USD" ? "$" : r.code === "EUR" ? "€" : r.code === "GBP" ? "£" : "د"}</div><div className="currency-name"><strong>{r.code}</strong><span>{r.name}</span></div><div className="rate-number"><span>شراء</span><strong>{r.buy}</strong></div><div className="rate-number"><span>بيع</span><strong>{r.sell}</strong></div><div className={r.up ? "rate-change up" : "rate-change down"}>{r.change}</div></div>)}</div><button className="see-all">عرض جميع العملات <ChevronLeft size={15}/></button></section></div>
   <section className="panel transactions"><div className="panel-head"><div><h3>آخر العمليات</h3><p>تتبع أحدث حركات الصندوق</p></div><button className="primary-button" onClick={() => setShowTx(true)}><Plus size={17}/> عملية جديدة</button></div><div className="table-tools"><label><Search size={16}/><input placeholder="ابحث باسم العميل أو رقم العملية" value={query} onChange={e => setQuery(e.target.value)}/>{query && <X size={14} onClick={() => setQuery("")}/>}</label><button className="filter-button"><SlidersHorizontal size={16}/> تصفية</button><button className="filter-button"><Download size={16}/> تصدير</button></div><div className="table-wrap"><table><thead><tr><th>رقم العملية</th><th>العميل</th><th>نوع العملية</th><th>المبلغ</th><th>القيمة بالريال</th><th>الوقت</th><th>الحالة</th><th></th></tr></thead><tbody>{filtered.map(m => <tr key={m.id}><td className="mono">{m.id}</td><td><div className="customer"><span><UserRound size={15}/></span><strong>{m.customer}</strong></div></td><td>{m.type}</td><td className="mono">{m.amount}</td><td className={m.color === "green" ? "positive mono" : "negative mono"}>{m.local}</td><td className="time"><Clock3 size={14}/>{m.time}</td><td><span className={`badge ${m.color}`}>{m.status}</span></td><td><button className="row-more"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div><button className="all-transactions">عرض كل العمليات <ChevronLeft size={15}/></button></section>
   {showTx && <div className="modal-backdrop" onClick={() => setShowTx(false)}><div className="transaction-modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setShowTx(false)}><X size={18}/></button><div className="modal-icon"><Wallet size={21}/></div><h3>عملية صرف جديدة</h3><p>أدخل تفاصيل العملية لإضافتها إلى سجل الصندوق.</p><label>نوع العملية<select><option value="buy">شراء عملة</option><option value="sell">بيع عملة</option></select></label><div className="modal-fields"><label>العملة<select><option>USD — دولار أمريكي</option><option>EUR — يورو</option><option>GBP — جنيه إسترليني</option></select></label><label>المبلغ<input placeholder="0.00" /></label></div><label>اسم العميل<input placeholder="اكتب اسم العميل" /></label><button className="primary-button full" onClick={saveTransaction}>حفظ العملية <CheckCircle2 size={17}/></button></div></div>}
 </div>
}
