# Generated by Django 5.2.17 on 2026-08-30 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_backend', '0002_employeedocument_performancereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('entity', models.CharField(max_length=120)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=220)),
                ('location', models.CharField(max_length=220)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('planned_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'تخطيط'), ('active', 'نشط'), ('on_hold', 'متوقف'), ('complete', 'مكتمل')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='exchange_backend.constructionclient')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('issue_type', models.CharField(default='مخاطر', max_length=80)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('progress', 'قيد المعالجة'), ('closed', 'مغلقة')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='exchange_backend.constructionproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCostTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('transaction_date', models.DateField()),
                ('source_type', models.CharField(default='expense', max_length=60)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_transactions', to='exchange_backend.constructionproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('phase', models.CharField(max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('todo', 'لم تبدأ'), ('progress', 'قيد التنفيذ'), ('done', 'مكتملة'), ('blocked', 'متعثرة')], default='todo', max_length=20)),
                ('is_critical', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='exchange_backend.constructionproject')),
            ],
        ),
    ]
